// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2VRg2SjL-93bAruKIyOSIvlWI81lEBzo',
    appId: '1:82751894044:web:b0f562066fb075469d65d9',
    messagingSenderId: '82751894044',
    projectId: 'twitter-official-1',
    authDomain: 'twitter-official-1.firebaseapp.com',
    storageBucket: 'twitter-official-1.appspot.com',
    measurementId: 'G-SLDPVEBBYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhIeltRJ5O0mQRgvu-Zjlx098TrSIfwYI',
    appId: '1:82751894044:android:0badd3f4a9180f4b9d65d9',
    messagingSenderId: '82751894044',
    projectId: 'twitter-official-1',
    storageBucket: 'twitter-official-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi74BrzDZxP1hlxP8jkaCtfMcN-YLZYfQ',
    appId: '1:82751894044:ios:17f0a5f8994115839d65d9',
    messagingSenderId: '82751894044',
    projectId: 'twitter-official-1',
    storageBucket: 'twitter-official-1.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi74BrzDZxP1hlxP8jkaCtfMcN-YLZYfQ',
    appId: '1:82751894044:ios:5373b3de54d9455a9d65d9',
    messagingSenderId: '82751894044',
    projectId: 'twitter-official-1',
    storageBucket: 'twitter-official-1.appspot.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
